run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 50

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - unused
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
