#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
	CREATE EXTENSION IF NOT EXISTS pgcrypto;

	ALTER DATABASE ${POSTGRES_DB} SET timezone TO 'UTC';

	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
	GRANT ALL ON SCHEMA public TO ${POSTGRES_USER};
EOSQL
